using System;

namespace Dippy.DDApi.Attributes
{
    /// <summary>
    /// Atribute used to identify
    /// </summary>
    [AttributeUsage(AttributeTargets.Property)]
    public class KeyAttribute : Attribute
    {
        /// <summary>
        /// Order of the key. Used for tables with multiple keys.
        /// </summary>
        public int Order { get; }
        /// <summary>
        /// Defines if the key is auto generated by the database.
        /// </summary>
        /// <remarks>
        /// This serves the same purpose as <see cref="ReadOnlyColumnAttribute"/>.
        /// </remarks>
        public bool IsAutoGenerated { get; }

        public KeyAttribute(bool isAutoGenerated = true, int order = 0)
        {
            IsAutoGenerated = isAutoGenerated;
            Order = order;
        }
    }
}
